analyzer:
  plugins:
    - import_lint
  errors:
    unused_import: ignore
    undefined_shown_name: ignore

import_lint:
  rules:
    use_case_rule:
      target_file_path: "use_case/*_use_case.dart"
      not_allow_imports: ["use_case/*_use_case.dart"]
      exclude_imports: ["use_case/base_use_case.dart"]
    repository_rule:
      target_file_path: "repository/*_repository.dart"
      not_allow_imports:
        [
          "use_case/*_use_case.dart",
          "repository/*_repository.dart",
          "space\ test/*.dart",
          "repository/sub/**/*.dart",
        ]
      exclude_imports: []
    package_rule:
      target_file_path: "**/*.dart"
      not_allow_imports: ["package:import_lint/import_lint.dart"]
      exclude_imports: []
    example_package_rule:
      target_file_path: "**/*.dart"
      not_allow_imports: ["package:example/**/test_two_use_case.dart"]
      exclude_imports: []
