analyzer:
  plugins:
    - import_lint
  errors:
    unused_import: ignore
    undefined_shown_name: ignore

import_lint:
  rules:
    use_case_rule:
      target_file_path: "/**/use_case/*_use_case.dart"
      not_allow_imports: ["/**/use_case/*_use_case.dart"]
      exclude_imports: ["/lib/use_case/base_use_case.dart"]
    repository_rule:
      target_file_path: "/**/repository/*_repository.dart"
      not_allow_imports:
        [
          "/**/use_case/*_repository.dart",
          "/**/use_case/*_use_case.dart",
          "/**/space\ test/*.dart",
        ]
      exclude_imports: []
