analyzer:
  plugins:
    - import_lint

import_lint:
  rules:
    use_case_rule:
      search_file_path: "/**/use_case/*_use_case.dart"
      not_allow_imports: ["/**/use_case/*_use_case.dart"]
      exclude_imports: ["/lib/use_case/base_use_case.dart"]
    repository_rule:
      search_file_path: "/**/repository/*_repository.dart"
      not_allow_imports:
        ["/**/use_case/*_repository.dart", "/**/use_case/*_use_case.dart"]
      exclude_imports: []
