name: import_lint
description: The Import Lint package defines import lint rules and report on lints found in Dart code.
version: 0.2.1
homepage: https://kawa.dev
repository: https://github.com/kawa1214/import-lint

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ">=2.1.0 <3.0.0"
  path: ">=1.8.0 <2.0.0"
  analyzer_plugin: ^0.8.0
  yaml: ">=3.1.0 <4.0.0"

dev_dependencies:
  lints: ^1.0.0
