name: import_lint_loader
description: bootstrap package of import_lint
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # import_lint:
  #   path: /Users/xxx/import-lint
  import_lint: ^1.0.1
