name: import_lint_loader
description: bootstrap package of import_lint
version: 0.9.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  import_lint:
    path: /Users/ryo/Documents/packages/import_lint_test/import-lint
  # import_lint: ^0.9.0
