name: dart test

on: [pull_request]

jobs:
  build:
    name: Dart Test
    runs-on: ubuntu-latest
    container:
      image: dart:2.18.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Install lcov
        run: apt-get install lcov
      - name: Install genhtml
        run: sudo apt-get install genhtml
      - name: run tool/test.sh
        run: bash tool/test.sh
