name: dart test

on: [pull_request]

jobs:
  build:
    name: Dart Test
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: run tool/test.sh
        run: bash tool/test.sh
