name: dart test

on: [pull_request]

jobs:
  build:
    name: Dart Test
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: at-wat/setup-gh-pr-comment@v0
      - name: Install dependencies
        run: dart pub get
      - name: run tool/test.sh
        run: bash tool/test.sh
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov/coverage.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./
